### ISSUE TITLE
[dev] Text appears misaligned on mobile view

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot.com#40]
![screenshot_2019-02-12-17-23-26](https://user-images.githubusercontent.com/11968358/52675353-35b93300-2eec-11e9-9f35-f790d29aad46.png)
Some text appears to be off-center in the mobile view of the homepage. This appears to only happen when the screen is in vertical mode. Using Google Chrome on Android.

**Comment by nsylke** [comment]
This can be reproduced on any browser by shrinking it until it no longer can.

**Comment by nsylke** [comment]
This no longer occurs, even with the new grid system in place.
